import  "./globals.css"
import Header from "./component/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
     
    >
      <body className="min-h-full flex flex-col">

  <Header/>  
        <main>{children}</main>

         
      </body>
    </html>
  );
}
